"""add normalized sources

Revision ID: 214ca03fb3ed
Revises: deef19cb438c
Create Date: 2026-07-15 02:51:37.507907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision: str = '214ca03fb3ed'
down_revision: Union[str, Sequence[str], None] = 'deef19cb438c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def _backfill_sources() -> None:
    connection = op.get_bind()

    legacy_sources = connection.execute(
        sa.text(
            """
            SELECT
                source,
                MIN(language) AS language,
                COUNT(DISTINCT language) AS language_count
            FROM articles
            WHERE source IS NOT NULL
              AND TRIM(source) <> ''
            GROUP BY source
            ORDER BY source
            """
        )
    ).mappings()

    sources_table = sa.table(
        "sources",
        sa.column("identifier", sa.String),
        sa.column("name", sa.String),
        sa.column("source_type", sa.String),
        sa.column("primary_jurisdiction", sa.String),
        sa.column("default_language", sa.String),
        sa.column("created_at", sa.DateTime),
    )

    created_at = datetime.now(timezone.utc)
    source_rows = []

    for legacy_source in legacy_sources:
        default_language = (
            legacy_source["language"]
            if legacy_source["language_count"] == 1
            else None
        )

        source_rows.append(
            {
                "identifier": legacy_source["source"],
                "name": legacy_source["source"],
                "source_type": "news_media",
                "primary_jurisdiction": None,
                "default_language": default_language,
                "created_at": created_at,
            }
        )

    if source_rows:
        connection.execute(
            sources_table.insert(),
            source_rows,
        )
    connection.execute(
        sa.text(
            """
            UPDATE articles
            SET source_id = (
                SELECT sources.id
                FROM sources
                WHERE sources.identifier = articles.source
            )
            WHERE source IS NOT NULL
              AND TRIM(source) <> ''
            """
        )
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('news_media', 'news_agency', 'government', 'international_organization', 'research_institution', 'social_media', 'other', name='source_type', native_enum=False, length=50), nullable=False),
    sa.Column('primary_jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('default_language', sa.String(length=35), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_default_language'), ['default_language'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_identifier'), ['identifier'], unique=True)
        batch_op.create_index(batch_op.f('ix_sources_primary_jurisdiction'), ['primary_jurisdiction'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_source_type'), ['source_type'], unique=False)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_articles_source_id'), ['source_id'], unique=False)
        batch_op.create_foreign_key(
            "fk_articles_source_id_sources",
            "sources",
            ["source_id"],
            ["id"],
        )
    _backfill_sources()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_articles_source_id_sources",
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f('ix_articles_source_id'))
        batch_op.drop_column('source_id')

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_source_type'))
        batch_op.drop_index(batch_op.f('ix_sources_primary_jurisdiction'))
        batch_op.drop_index(batch_op.f('ix_sources_identifier'))
        batch_op.drop_index(batch_op.f('ix_sources_default_language'))

    op.drop_table('sources')
    # ### end Alembic commands ###
