"""add retrieval attempts

Revision ID: 2aa55e015b7d
Revises: 85db1d6a8b3a
Create Date: 2026-07-19 02:28:57.677804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa55e015b7d'
down_revision: Union[str, Sequence[str], None] = '85db1d6a8b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retrieval_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('connector_id', sa.String(length=100), nullable=False),
    sa.Column('connector_version', sa.String(length=100), nullable=False),
    sa.Column('requested_location', sa.String(length=2048), nullable=False),
    sa.Column('external_identifier', sa.String(length=2048), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.Enum('succeeded', 'failed', 'unavailable', 'access_restricted', name='retrieval_outcome', native_enum=False, length=50), nullable=False),
    sa.Column('resolved_location', sa.String(length=2048), nullable=True),
    sa.Column('response_status', sa.String(length=100), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('hash_algorithm', sa.String(length=50), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='fk_retrieval_attempts_article_id_articles'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['collection_endpoints.id'], name='fk_retrieval_attempts_endpoint_id_collection_endpoints'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retrieval_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retrieval_attempts_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieval_attempts_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieval_attempts_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieval_attempts_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieval_attempts_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieval_attempts_retrieved_at'), ['retrieved_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retrieval_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retrieval_attempts_retrieved_at'))
        batch_op.drop_index(batch_op.f('ix_retrieval_attempts_outcome'))
        batch_op.drop_index(batch_op.f('ix_retrieval_attempts_endpoint_id'))
        batch_op.drop_index(batch_op.f('ix_retrieval_attempts_content_hash'))
        batch_op.drop_index(batch_op.f('ix_retrieval_attempts_connector_id'))
        batch_op.drop_index(batch_op.f('ix_retrieval_attempts_article_id'))

    op.drop_table('retrieval_attempts')
    # ### end Alembic commands ###
