"""add collection endpoints

Revision ID: 85db1d6a8b3a
Revises: 214ca03fb3ed
Create Date: 2026-07-19 01:39:29.595518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85db1d6a8b3a'
down_revision: Union[str, Sequence[str], None] = '214ca03fb3ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('endpoint_type', sa.Enum('rss', 'atom', 'rest_api', 'oai_pmh', 'iiif', 'sdmx', 'sparql', 'sitemap', 'web_archive', 'dataset_catalog', 'other', name='endpoint_type', native_enum=False, length=50), nullable=False),
    sa.Column('connector_id', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('language', sa.String(length=35), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name='fk_collection_endpoints_source_id_sources'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_id', 'url', name='uq_collection_endpoint_connector_url')
    )
    with op.batch_alter_table('collection_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_endpoints_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_endpoints_endpoint_type'), ['endpoint_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_endpoints_identifier'), ['identifier'], unique=True)
        batch_op.create_index(batch_op.f('ix_collection_endpoints_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_endpoints_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_collection_endpoints_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_endpoints_source_id'))
        batch_op.drop_index(batch_op.f('ix_collection_endpoints_language'))
        batch_op.drop_index(batch_op.f('ix_collection_endpoints_is_active'))
        batch_op.drop_index(batch_op.f('ix_collection_endpoints_identifier'))
        batch_op.drop_index(batch_op.f('ix_collection_endpoints_endpoint_type'))
        batch_op.drop_index(batch_op.f('ix_collection_endpoints_connector_id'))

    op.drop_table('collection_endpoints')
    # ### end Alembic commands ###
