"""add acquisition candidates

Revision ID: b22c36e940db
Revises: cb3e06323fb8
Create Date: 2026-07-21 22:16:54.320552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22c36e940db'
down_revision: Union[str, Sequence[str], None] = 'cb3e06323fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisition_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('connector_id', sa.String(length=100), nullable=False),
    sa.Column('connector_version', sa.String(length=100), nullable=False),
    sa.Column('external_identifier', sa.String(length=2048), nullable=True),
    sa.Column('location', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('media_type', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=35), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discovery_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('discovery_count >= 1', name='ck_acquisition_candidates_discovery_count_positive'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='fk_acquisition_candidates_article_id_articles'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['collection_endpoints.id'], name='fk_acquisition_candidates_endpoint_id_collection_endpoints'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_id', 'fingerprint', name='uq_acquisition_candidate_endpoint_fingerprint')
    )
    with op.batch_alter_table('acquisition_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acquisition_candidates_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_candidates_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_candidates_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_candidates_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_candidates_first_discovered_at'), ['first_discovered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_candidates_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_candidates_last_discovered_at'), ['last_discovered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_candidates_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_candidates_source_identifier'), ['source_identifier'], unique=False)

    with op.batch_alter_table('retrieval_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_retrieval_attempts_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_foreign_key('fk_retrieval_attempts_candidate_id_acquisition_candidates', 'acquisition_candidates', ['candidate_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retrieval_attempts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_retrieval_attempts_candidate_id_acquisition_candidates', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_retrieval_attempts_candidate_id'))
        batch_op.drop_column('candidate_id')

    with op.batch_alter_table('acquisition_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acquisition_candidates_source_identifier'))
        batch_op.drop_index(batch_op.f('ix_acquisition_candidates_published_at'))
        batch_op.drop_index(batch_op.f('ix_acquisition_candidates_last_discovered_at'))
        batch_op.drop_index(batch_op.f('ix_acquisition_candidates_language'))
        batch_op.drop_index(batch_op.f('ix_acquisition_candidates_first_discovered_at'))
        batch_op.drop_index(batch_op.f('ix_acquisition_candidates_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_acquisition_candidates_endpoint_id'))
        batch_op.drop_index(batch_op.f('ix_acquisition_candidates_connector_id'))
        batch_op.drop_index(batch_op.f('ix_acquisition_candidates_article_id'))

    op.drop_table('acquisition_candidates')
    # ### end Alembic commands ###
