"""add raw artifacts

Revision ID: cb3e06323fb8
Revises: 2aa55e015b7d
Create Date: 2026-07-20 11:45:28.684032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3e06323fb8'
down_revision: Union[str, Sequence[str], None] = '2aa55e015b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_algorithm', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_backend', sa.String(length=100), nullable=False),
    sa.Column('storage_key', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('byte_size >= 0', name='ck_raw_artifacts_byte_size_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_algorithm', 'content_hash', name='uq_raw_artifact_digest'),
    sa.UniqueConstraint('storage_backend', 'storage_key', name='uq_raw_artifact_storage_location')
    )
    with op.batch_alter_table('raw_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_artifacts_storage_backend'), ['storage_backend'], unique=False)

    with op.batch_alter_table('retrieval_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_artifact_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_retrieval_attempts_raw_artifact_id'), ['raw_artifact_id'], unique=False)
        batch_op.create_foreign_key('fk_retrieval_attempts_raw_artifact_id_raw_artifacts', 'raw_artifacts', ['raw_artifact_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retrieval_attempts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_retrieval_attempts_raw_artifact_id_raw_artifacts', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_retrieval_attempts_raw_artifact_id'))
        batch_op.drop_column('raw_artifact_id')

    with op.batch_alter_table('raw_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_artifacts_storage_backend'))

    op.drop_table('raw_artifacts')
    # ### end Alembic commands ###
