"""create initial schema

Revision ID: deef19cb438c
Revises:
Create Date: 2026-07-14 18:28:00.963862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deef19cb438c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_url'), ['url'], unique=True)

    op.create_table('discourse_analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('method_version', sa.String(length=50), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('sentence_count', sa.Integer(), nullable=False),
    sa.Column('average_sentence_length', sa.Float(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('exclamation_count', sa.Integer(), nullable=False),
    sa.Column('first_person_plural_count', sa.Integer(), nullable=False),
    sa.Column('third_person_plural_count', sa.Integer(), nullable=False),
    sa.Column('certainty_marker_count', sa.Integer(), nullable=False),
    sa.Column('uncertainty_marker_count', sa.Integer(), nullable=False),
    sa.Column('fear_marker_count', sa.Integer(), nullable=False),
    sa.Column('threat_marker_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'method_version', name='uq_discourse_article_method')
    )
    with op.batch_alter_table('discourse_analysis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discourse_analysis_results_article_id'), ['article_id'], unique=False)

    op.create_table('processing_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('parsing', 'discourse', name='processing_stage', native_enum=False, length=50), nullable=False),
    sa.Column('method_version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='processing_status', native_enum=False, length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'stage', 'method_version', name='uq_processing_article_stage_method')
    )
    with op.batch_alter_table('processing_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_states_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_states_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_states_status'), ['status'], unique=False)

    op.create_table('analysis_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_result_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('matched_terms', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['discourse_analysis_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_evidence_analysis_result_id'), ['analysis_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_evidence_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_evidence_category'))
        batch_op.drop_index(batch_op.f('ix_analysis_evidence_analysis_result_id'))

    op.drop_table('analysis_evidence')
    with op.batch_alter_table('processing_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_states_status'))
        batch_op.drop_index(batch_op.f('ix_processing_states_stage'))
        batch_op.drop_index(batch_op.f('ix_processing_states_article_id'))

    op.drop_table('processing_states')
    with op.batch_alter_table('discourse_analysis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discourse_analysis_results_article_id'))

    op.drop_table('discourse_analysis_results')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_url'))
        batch_op.drop_index(batch_op.f('ix_articles_id'))
        batch_op.drop_index(batch_op.f('ix_articles_content_hash'))

    op.drop_table('articles')
    # ### end Alembic commands ###
